"""finish tables

Revision ID: 1dae7ccc4c63
Revises: f8f144bf1cdf
Create Date: 2020-04-14 20:58:51.626131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dae7ccc4c63'
down_revision = 'f8f144bf1cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('searchTime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_results_searchTime'), 'results', ['searchTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_searchTime'), table_name='results')
    op.drop_column('results', 'searchTime')
    # ### end Alembic commands ###
