"""users table

Revision ID: f8f144bf1cdf
Revises: 
Create Date: 2020-04-13 21:32:04.496343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f144bf1cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardName', sa.String(length=32), nullable=True),
    sa.Column('cardSet', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_cardName'), 'card', ['cardName'], unique=False)
    op.create_index(op.f('ix_card_cardSet'), 'card', ['cardSet'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siteLink', sa.String(length=32), nullable=True),
    sa.Column('siteName', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_siteLink'), 'site', ['siteLink'], unique=True)
    op.create_index(op.f('ix_site_siteName'), 'site', ['siteName'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cardId', sa.Integer(), nullable=True),
    sa.Column('siteId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cardId'], ['card.id'], ),
    sa.ForeignKeyConstraint(['siteId'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_site_siteName'), table_name='site')
    op.drop_index(op.f('ix_site_siteLink'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_card_cardSet'), table_name='card')
    op.drop_index(op.f('ix_card_cardName'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
